services:
  server:
    build:
      context: .
    restart: always
    env_file:
      - ./.envs/.django
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:17
    restart: always
    user: postgres
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    ports:
      - 5437:5432
volumes:
  db-data:
